# -*- coding: utf-8 -*-
"""4_Doc_Similarity(TFIDF)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H5A9ZF3W2RMn2TVZHA9cXWD88GZVprhJ
"""

import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

sent = ('휴일 인 오늘 도 서쪽 을 중심 으로 폭염 이 이어졌는데요. 내일 은 반가운 비 소식 이 있습니다',
        '폭염 을 피해서 휴일 에 놀러왔다가 갑작스런 비 로 인해 망연자실 하고 있습니다')

tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(sent).toarray()
print(np.round(tfidf_matrix, 3))

# 자카드 유사도
sent1 = set((sent[0].split()))
sent2 = set(sent[1].split())
print(sent1); print(sent2)

# 합집합과 교지합
hap_set = sent1 | sent2
gyo_set = sent1 & sent2
print(hap_set)
print(gyo_set)
jaccard = len(gyo_set) / len(hap_set)
print(jaccard)

# 코사인 유사도
from sklearn.metrics.pairwise import cosine_similarity

d = cosine_similarity(tfidf_matrix[0:1], tfidf_matrix[1:2])
print(d)

# 유클리디안 유사도
from sklearn.metrics.pairwise import euclidean_distances
euclidean_distances(tfidf_matrix[0:1], tfidf_matrix[1:2])

def l1_normalize(v):
  return v / np.sum(v)

tfidf_norm_l1 = l1_normalize(tfidf_matrix)
d = euclidean_distances(tfidf_norm_l1[0:1], tfidf_norm_l1[1:2])
print(d)